---
 - hosts: all
   tasks:
     vars:
       tomcat_version: 8.5.23
       tomcat_permissions_production: True
       tomcat_users:
         - username: "tomcat"
           password: "t3mpp@ssw0rd"
           roles: " tomcat,admin,manager,manager-gui"
         - username: "exampleuser"
           password: "us3rp@ssw0rd"
           roles: "tomcat"
     roles:
       - role: zaxos.tomcat-ansible-role
     when: ansible_facts['os_family'] == 'RedHat'
     become: yes
     become_method: sudo
     roles:
       #- oracle-java8
       #- tomcat-jenkins
       #- jenkins-slave
       #- nginx
        - tomcat
     when: ansible_facts['os_family'] == 'Debian'
     tasks:
       - win_chocolatey:
         name:
           - tomcat
         state: present
     when: ansible_facts['os_family'] == 'Windows'



