- hosts: linux

  tasks:
    - name: Download war file from artifactory
      get_url:
        url: "http://192.168.1.130:8081/artifactory/java-app/java-sample-app-1.0.0.war"
        dest: "/opt/tomcat/webapps/"

