---
- name: installing java 8 on ubuntu
  command: "{{ item }}"
  with_items:
#    - sudo apt-get install default-jdk -y  
    - sudo apt-get install wget -y
    - sudo apt-get install python-software-properties -y
    - sudo add-apt-repository ppa:webupd8team/java
    - sudo apt-get update
    - sudo apt-get install oracle-java8-installer -y

- name: Run a script
  script: /etc/ansible/workspace/javatom_try/templates/tom1.sh

- name: Add the user 'tomcat' with a  primary group of 'tomcat'
  user:
    name: tomcat
    comment: tomcat user
    group: tomcat
- name: Ensure group "tomcat" exists
  group:
    name: tomcat
    state: present
- file:
    path: /opt/tomcat
    mode: 755
    state: directory 
  become: yes
  when: ansible_os_family == "Debian"
- name: installing tomcat tar file
  unarchive:
    src: http://www-us.apache.org/dist/tomcat/tomcat-8/v8.5.40/bin/apache-tomcat-8.5.40.tar.gz
    dest: /opt/tomcat
    mode: 755 
    remote_src: yes
  become: yes
- name: change mode
  command: chmod +x bin/
  args:
    chdir: /opt/tomcat/apache-tomcat-8.5.40
  become: yes
- name: change mode
  command: chown -hR tomcat:tomcat tomcat
  args:
    chdir: /opt/tomcat
  become: yes
- name: Run a script
  script: /etc/ansible/workspace/javatom_try/templates/tom2.sh

- template:
    src: tomcat-users.xml 
    dest: /opt/tomcat/apache-tomcat-8.5.40/conf/tomcat-users.xml
    mode: 755
  become: yes
- template:
    src: context.xml
    dest: /opt/tomcat/apache-tomcat-8.5.40/webapps/manager/META-INF/context.xml
    mode: 755
  become: yes
- name: Run a script 
  script: /etc/ansible/workspace/javatom_try/templates/tom4.sh
- template:
    src: tomcat.service
    dest: /etc/systemd/system/tomcat.service
    mode: 755
  become: yes
- name: Run a script
  script: /etc/ansible/workspace/javatom_try/templates/tom3.sh
#- name: start tomcat
#command: ./startup.sh
#  args:
#    chdir: /opt/tomcat/apache-tomcat-8.5.40/bin

- name: Download war file from artifactory
  get_url:
    url: "http://192.168.1.130:8081/artifactory/Ansible-Java-Sourcecode-POC/newapp-0.0.1-SNAPSHOT.war"
    dest: "/opt/tomcat/apache-tomcat-8.5.40/webapps"
  when: ansible_facts['os_family'] == 'Debian'



